[DEFAULT]
interval=10
mqttServer=192.168.88.44
mqttPort=1883
mqttUsername=mqtttest
mqttPassword=mqtttest
deviceNameForTopic=download-server
topicTemplate=tele/{{deviceNameForTopic}}/SENSOR
deviceNameDisplayText=Download Server
#servicesFile=
services=adguardhome.service,deluged.service,deluge-web.service,grott-ha.service,jackett.service,radarr.service,sabnzbd.service,sonarr.service
